iFixit API: have a little more grace
iFixit/pim-community-standard pull request #20
Opened 2022-08-26 23:07 UTC by danielbeardsley

This is a fast API (10-20ms), yet we still see occasional timeouts.
Just retry in this case, cause if the original request took longer
than 3s, it'll probably never finish and must have got lost in the
shuffle.

Closes https://github.com/iFixit/ifixit/issues/44076

2022-08-30 14:54 UTC, davidrans requested changes
CR :coffee:

2022-08-30 14:54 UTC, davidrans commented on src/iFixit/EventListener/iFixitApi.php
> +use GuzzleHttp\{Client, HandlerStack, Middleware, RetryMiddleware};
```suggestion
use GuzzleHttp\{Client, HandlerStack, Middleware};
```

2022-08-30 14:54 UTC, davidrans approved these changes

2022-08-30 14:54 UTC, davidrans approved these changes
CR :coffee:

2022-08-30 15:37 UTC, k0rvusk0r4x commented
Not sure how to go about testing this. Basically, just want to make sure it's not going to bog anything down with retries to the point it somehow make things worse overall. (I don't really see that happening with an API that is naturally fast, though.)

2022-09-06 15:49 UTC, k0rvusk0r4x commented
Thoughts on how to test [this], @danielbeardsley?

2022-09-06 16:40 UTC, danielbeardsley commented
QA:

1. From dev, run `dev-akeneo` to SSH into the akeneo machine
2. `cd /opt/akeneo`
3. fetch and checkout this branch
4. `make down && make up`
5. Click "save" on a product in Akeneo
6. Ensure product data has updated by visiting the product page (OR tail the debug log in `/home/ifixit/Code`)

2022-09-06 18:36 UTC, k0rvusk0r4x commented
Followed steps one through four [here](https://github.com/iFixit/pim-community-standard/pull/20#issuecomment-1238398178).
When I went to akeneo.cominor.com, I got this:
![image](https://user-images.githubusercontent.com/33426643/188712840-c206380b-411d-435b-a8cf-32e92012a601.png)

dev_block 😿

2022-09-06 20:33 UTC, danielbeardsley commented on src/iFixit/EventListener/iFixitApi.php
> +      });
```suggestion
      }));
```

I guess we don't have a syntax check for CI on this repo ;-)

2022-09-07 00:10 UTC, danielbeardsley commented
un_dev_block :+1: 
 
Derp, thanks @k0rvusk0r4x !

2022-09-07 19:25 UTC, mlahargou approved these changes
CR 📱

2022-09-07 21:33 UTC, deltuh-vee commented
QA 🎬 
Akeneo product updates still work with this change.

2022-09-07 22:52 UTC, merged